"""empty message

Revision ID: 68144dfa911b
Revises: 98765e71195b
Create Date: 2025-05-24 21:45:50.122393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68144dfa911b'
down_revision = '98765e71195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naming', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summa', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('categ_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categ_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('checks')
    op.drop_table('categories')
    # ### end Alembic commands ###
