"""posts table

Revision ID: 98765e71195b
Revises: 8c230f05079c
Create Date: 2025-05-24 21:42:27.691437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98765e71195b'
down_revision = '8c230f05079c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('check_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'categories', ['categ_id'], ['id'])
        batch_op.create_foreign_key(None, 'checks', ['check_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('check_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
