"""empty message

Revision ID: c971eb05dc88
Revises: 8c0e59c05312
Create Date: 2025-05-24 15:00:07.247272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c971eb05dc88'
down_revision = '8c0e59c05312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_categories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('naming',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categ_id', sa.Integer(), nullable=False))
        batch_op.alter_column('check_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'checks', ['check_id'], ['id'])
        batch_op.alter_column('check_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('categ_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('naming',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('_alembic_tmp_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naming', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
